- name: Launch fronted container
  docker_container:
    name: httpd
    image: anesosz/fronted:2.4
    ports:
      - "80:80"
    networks:
      - name: my_network
  vars:
    ansible_python_interpreter: /usr/bin/python3
