- name: Launch application container
  docker_container:
    name: backend
    image: anesosz/backend:1.0
    networks:
      - name: my_network
    ports:
      - "8080:8080"
  vars:
    ansible_python_interpreter: /usr/bin/python3
