- name: Launch database container
  docker_container:
    name: database
    image: anesosz/database:14.1-alpine
    env:
      POSTGRES_DB: db
      POSTGRES_USER: usr
      POSTGRES_PASSWORD: pwd
    networks:
      - name: my_network
  vars:
    ansible_python_interpreter: /usr/bin/python3
